/**
 * Last-resort fallback when /catalog-tables API is unavailable.
 * Keep aligned with catalog_definitions.json; prefer API as source of truth.
 */
export const FALLBACK_CATALOG_TABLES = [
    {
        name: 'skus',
        label: 'Productos (SKUs)',
        target_schema: 'public',
        target_table: 'skus',
        required_columns: [
            'organization_id',
            'sku',
            'name',
            'status',
            'subcategory',
            'class',
            'subclass',
            'attr_1',
            'attr_2',
            'attr_3',
            'attr_4',
            'attr_5',
            'attr_6',
            'vendor_id',
        ],
        optional_columns: ['category', 'brand'],
        required_mapping_columns: [
            'sku',
            'name',
            'status',
            'subcategory',
            'class',
            'subclass',
            'attr_1',
            'attr_2',
            'attr_3',
            'attr_4',
            'attr_5',
            'attr_6',
            'vendor_id',
        ],
        unique_keys: ['sku'],
        ignored_file_headers: [
            'sku_id',
            'organization_id',
            'created_at',
            'updated_at',
            'imported_at',
        ],
        non_mappable_targets: [
            'sku_id',
            'id',
            'organization_id',
            'created_at',
            'updated_at',
            'imported_at',
        ],
        enums: { status: ['active', 'inactive', 'discontinued', 'new_launch'] },
        validation_hints: [
            'Clave única (PK): sku',
            'status es obligatorio en el mapping',
            'organization_id se asigna automáticamente del usuario',
        ],
        column_aliases: {
            organization_id: ['organization_id', 'org_id', 'organization'],
            sku: ['sku', 'code', 'sku_code', 'product_code'],
            name: ['name', 'sku_name', 'product_name', 'description'],
            category: ['category', 'categoria'],
            brand: ['brand', 'marca'],
            status: ['status', 'estado'],
        },
    },
    {
        name: 'location',
        label: 'Ubicaciones',
        target_schema: 'public',
        target_table: 'locations',
        required_columns: [
            'code',
            'name',
            'loc_type',
            'country',
            'state',
            'city',
            'timezone',
            'status',
        ],
        optional_columns: [],
        required_mapping_columns: [
            'code',
            'name',
            'loc_type',
            'country',
            'state',
            'city',
            'timezone',
            'status',
        ],
        unique_keys: ['organization_id', 'code'],
        ignored_file_headers: [
            'location_id',
            'locationid',
            'organization_id',
            'created_at',
            'updated_at',
        ],
        non_mappable_targets: [
            'location_id',
            'organization_id',
            'created_at',
            'updated_at',
        ],
        enums: {
            loc_type: [
                'store',
                'warehouse',
                'distribution_center',
                'plant',
                'dark_store',
                'region',
                'virtual',
            ],
            status: ['active', 'inactive'],
        },
        validation_hints: [
            'Clave única: (organization_id, code)',
            'code es el código de negocio (no uses location_id del archivo)',
            'organization_id se asigna automáticamente del usuario',
        ],
        column_aliases: {
            organization_id: ['organization_id', 'org_id', 'organization'],
            code: ['code', 'location_code', 'loc_code'],
            name: ['name', 'location_name', 'location', 'store_name'],
            country: ['country', 'pais', 'país'],
            state: ['state', 'estado', 'province'],
            city: ['city', 'ciudad'],
            timezone: ['timezone', 'tz'],
            status: ['status', 'is_active', 'active'],
            loc_type: ['loc_type', 'location_type', 'type'],
        },
    },
];
